
abm_dummies = {'policies': ['POLICIES_buy', 'POLICIES_rent', 'POLICIES_wage', 'POLICIES_no_policy'],
               'interest': ['INTEREST_fixed', 'INTEREST_real', 'INTEREST_nominal'],
               'acps': ['PROCESSING_ACPS_BELO HORIZONTE',
                        'PROCESSING_ACPS_FORTALEZA',
                        'PROCESSING_ACPS_PORTO ALEGRE',
                        'PROCESSING_ACPS_CAMPINAS',
                        'PROCESSING_ACPS_SALVADOR',
                        'PROCESSING_ACPS_RECIFE',
                        'PROCESSING_ACPS_SAO PAULO',
                        'PROCESSING_ACPS_JOINVILLE',
                        'PROCESSING_ACPS_CAMPO GRANDE',
                        'PROCESSING_ACPS_JUNDIAI',
                        'PROCESSING_ACPS_FEIRA DE SANTANA',
                        'PROCESSING_ACPS_IPATINGA',
                        'PROCESSING_ACPS_LONDRINA',
                        'PROCESSING_ACPS_SOROCABA',
                        'PROCESSING_ACPS_JOAO PESSOA',
                        'PROCESSING_ACPS_SAO JOSE DO RIO PRETO',
                        'PROCESSING_ACPS_MACEIO',
                        'PROCESSING_ACPS_SAO JOSE DOS CAMPOS',
                        'PROCESSING_ACPS_ILHEUS - ITABUNA',
                        'PROCESSING_ACPS_SAO LUIS',
                        'PROCESSING_ACPS_UBERLANDIA',
                        'PROCESSING_ACPS_MARINGA',
                        'PROCESSING_ACPS_VITORIA',
                        'PROCESSING_ACPS_CUIABA',
                        'PROCESSING_ACPS_BELEM',
                        'PROCESSING_ACPS_NOVO HAMBURGO - SAO LEOPOLDO',
                        'PROCESSING_ACPS_TERESINA',
                        'PROCESSING_ACPS_MANAUS',
                        'PROCESSING_ACPS_BRASILIA'],
               'r_wage': ['WAGE_IGNORE_UNEMPLOYMENT_False', 'WAGE_IGNORE_UNEMPLOYMENT_True'],
               'r_licenses': ['T_LICENSES_PER_REGION_False',
                              'T_LICENSES_PER_REGION_True',
                              'T_LICENSES_PER_REGION_random'],
               'days': ['STARTING_DAY_2000-01-01', 'STARTING_DAY_2000-01-01'],
               'r_municipal_fund': ['FPM_DISTRIBUTION_False', 'FPM_DISTRIBUTION_True'],
               'r_metro_fund': ['ALTERNATIVE0_False', 'ALTERNATIVE0_True']
               }

abm_params = ['CONSTRUCTION_ACC_CASH_FLOW',
              'HIRING_SAMPLE_SIZE',
              'LABOR_MARKET',
              'LOAN_PAYMENT_TO_PERMANENT_INCOME',
              'LOT_COST',
              'MARKUP',
              'MAX_LOAN_TO_VALUE',
              'MUNICIPAL_EFFICIENCY_MANAGEMENT',
              'NEIGHBORHOOD_EFFECT',
              'OFFER_SIZE_ON_PRICE',
              'PCT_DISTANCE_HIRING',
              'PERCENTAGE_ACTUAL_POP',
              'PERCENTAGE_ENTERING_ESTATE_MARKET',
              'PERCENT_CONSTRUCTION_FIRMS',
              'POLICY_COEFFICIENT',
              'POLICY_DAYS',
              'POLICY_QUANTILE',
              'PRIVATE_TRANSIT_COST',
              'PRODUCTIVITY_EXPONENT',
              'PRODUCTIVITY_MAGNITUDE_DIVISOR',
              'PUBLIC_TRANSIT_COST',
              'SIZE_MARKET',
              'STICKY_PRICES',
              'TAX_ESTATE_TRANSACTION',
              'TAX_PROPERTY',
              'TOTAL_DAYS']


